#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Nov 23, 2021 01:18:32 AM -03  platform: Windows NT
from tkinter import *
import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

class Toplevel1:
    def __init__(self):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'


        self.top = tk.Tk()
        self.top.geometry("600x450+333+117")
        self.top.minsize(120, 1)
        self.top.maxsize(1370, 749)
        self.top.resizable(1,  1)
        self.top.title("New Toplevel")
        self.top.configure(background="#050A30")
        self.top.configure(highlightbackground="#d9d9d9")
        self.top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.1, rely=0.067, relheight=0.833, relwidth=0.825)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#000c66")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Entry1 = tk.Entry(self.Frame1)
        self.Entry1.place(relx=0.115, rely=0.339, height=30, relwidth=0.695)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="blue")
        self.Entry1.configure(selectforeground="white")

        self.Entry2 = tk.Entry(self.Frame1, show = '*')
        self.Entry2.place(relx=0.115, rely=0.563, height=30, relwidth=0.695)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="blue")
        self.Entry2.configure(selectforeground="white")

        self.Login = tk.Label(self.Frame1)
        self.Login.place(relx=0.368, rely=0.056, height=43, width=130)
        self.Login.configure(activebackground="#000C66")
        self.Login.configure(activeforeground="white")
        self.Login.configure(activeforeground="black")
        self.Login.configure(background="#000C66")
        self.Login.configure(disabledforeground="#a3a3a3")
        self.Login.configure(font="-family {SimSun} -size 16 -weight bold")
        self.Login.configure(foreground="#ffffff")
        self.Login.configure(highlightbackground="#d9d9d9")
        self.Login.configure(highlightcolor="black")
        self.Login.configure(text='''Login''')

        self.Button1 = tk.Button(self.Frame1, command = self.verificaCadastro)
        self.Button1.place(relx=0.368, rely=0.677, height=44, width=107)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#0000FF")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {SimSun} -size 15")
        self.Button1.configure(foreground="#ffffff")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Logar''')

        self.Button1_1 = tk.Button(self.Frame1)
        self.Button1_1.place(relx=0.368, rely=0.816, height=44, width=107)
        self.Button1_1.configure(activebackground="#ececec")
        self.Button1_1.configure(activeforeground="#000000")
        self.Button1_1.configure(background="#0000FF")
        self.Button1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1.configure(font="-family {SimSun} -size 15")
        self.Button1_1.configure(foreground="#ffffff")
        self.Button1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1.configure(highlightcolor="black")
        self.Button1_1.configure(pady="0")
        self.Button1_1.configure(text='''Cadastrar''')

        self.Login_1 = tk.Label(self.Frame1)
        self.Login_1.place(relx=0.069, rely=0.451, height=33, width=130)
        self.Login_1.configure(activebackground="#000C66")
        self.Login_1.configure(activeforeground="white")
        self.Login_1.configure(activeforeground="black")
        self.Login_1.configure(background="#000C66")
        self.Login_1.configure(disabledforeground="#a3a3a3")
        self.Login_1.configure(font="-family {SimSun} -size 16 -weight bold")
        self.Login_1.configure(foreground="#ffffff")
        self.Login_1.configure(highlightbackground="#d9d9d9")
        self.Login_1.configure(highlightcolor="black")
        self.Login_1.configure(text='''Senha:''')

        self.Login_1_1 = tk.Label(self.Frame1)
        self.Login_1_1.place(relx=0.093, rely=0.224, height=33, width=129)
        self.Login_1_1.configure(activebackground="#000C66")
        self.Login_1_1.configure(activeforeground="white")
        self.Login_1_1.configure(activeforeground="black")
        self.Login_1_1.configure(background="#000C66")
        self.Login_1_1.configure(disabledforeground="#a3a3a3")
        self.Login_1_1.configure(font="-family {SimSun} -size 16 -weight bold")
        self.Login_1_1.configure(foreground="#ffffff")
        self.Login_1_1.configure(highlightbackground="#d9d9d9")
        self.Login_1_1.configure(highlightcolor="black")
        self.Login_1_1.configure(text='''Usuário:''')
        self.top.mainloop()
    
    def verificaCadastro(self):
        usuarioCorreto = 'admin'
        senhaCorreta = '123456'

        if self.Entry1.get() == 'admin' and self.Entry2.get() == '123456':
            print('Usuário logado!!')
            self.top.destroy()
            self.janela2()
        else:
            print('Usuário ou senha incorretos!')

    def janela2(self):
        root = tk.Tk()
        root.title('Usuário logado!')
        root.mainloop()

Toplevel1()
